# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Twitch Bot

site_dir: docs/templates/docs
docs_dir: docs/docs

theme:
  name: material
  favicon: assets/images/favicon.svg
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

repo_name: Ozy-Viking/twitch_bot
repo_url: https://github.com/Ozy-Viking/twitch_bot
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - toc:
      permalink: '#'
  - tables
  - attr_list
  - footnotes
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # - pymdownx.superfences:
  #     custom_fences:
  #         - name: mermaid
  #           class: mermaid
  #           format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
        alternate_style: true

copyright: Copyright &copy; 2023 Zack Hankin

extra:
  version:
    provider: mike
    default:
      - latest
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - search:
  - tags
  # - autorefs
  - mkdocstrings
  - mike:
      canonical_version: latest
      version_selector: true
      css_dir: assets/stylesheets
      javascript_dir: assets/javascripts
      # deploy_prefix: 'docs/'
  - offline

extra_css:
    - assets/stylesheets/custom.css

use_directory_urls: true

watch:
  - frontend
  - api
  - twitch_bot
exclude_docs: |
  *.py
  __pycache__/