// @ts-nocheck
import BoomerangURL from "/src/static/koth/images/Boomerang.png";
import Cat_RocketURL from "/src/static/koth/images/Cat_Rocket.png";
import GhostCatURL from "/src/static/koth/images/GhostCat.png";
import Goon_SackURL from "/src/static/koth/images/Goon_Sack.png";
import Grassy_HillURL from "/src/static/koth/images/Grassy_Hill.png";
import HerdURL from "/src/static/koth/images/Herd.png";
import Holding_Heart_CatURL from "/src/static/koth/images/Holding_Heart_Cat.png";
import IQ200URL from "/src/static/koth/images/IQ200.png";
import King_of_the_hill_barrows_editionURL from "/src/static/koth/images/King_of_the_hill_barrows_edition.png";
import King_of_the_hill_barrows_edition_2URL from "/src/static/koth/images/King_of_the_hill_barrows_edition_2.png";
import Litter_badgeURL from "/src/static/koth/images/Litter_badge.png";
import Mad_House_2URL from "/src/static/koth/images/Mad_House_2.png";
import Name_Butcher_4000URL from "/src/static/koth/images/Name_Butcher_4000.png";
import NukeURL from "/src/static/koth/images/Nuke.png";
import PumpkinURL from "/src/static/koth/images/Pumpkin.png";
import RingURL from "/src/static/koth/images/Ring.png";
import SpaghettiURL from "/src/static/koth/images/Spaghetti.png";
import WackURL from "/src/static/koth/images/Wack.png";
import WombatURL from "/src/static/koth/images/Wombat.png";
import cat_witchURL from "/src/static/koth/images/cat_witch.png";
import didgeridooURL from "/src/static/koth/images/didgeridoo.png";
import doughnutURL from "/src/static/koth/images/doughnut.png";
import factorioURL from "/src/static/koth/images/factorio.png";
import matchURL from "/src/static/koth/images/match.png";
import no1URL from "/src/static/koth/images/no1.png";
import panURL from "/src/static/koth/images/pan.png";
import plungerURL from "/src/static/koth/images/plunger.png";
import poopURL from "/src/static/koth/images/poop.png";
import purpleURL from "/src/static/koth/images/purple.png";
import sausage_sangaURL from "/src/static/koth/images/sausage_sanga.png";
import seaBusURL from "/src/static/koth/images/seaBus.png";
import secret_thongURL from "/src/static/koth/images/secret_thong.png";
import sleepURL from "/src/static/koth/images/sleep.png";
import teapotURL from "/src/static/koth/images/teapot.png";
import thongURL from "/src/static/koth/images/thong.png";

export const Boomerang=BoomerangURL;
export const Cat_Rocket=Cat_RocketURL;
export const GhostCat=GhostCatURL;
export const Goon_Sack=Goon_SackURL;
export const Grassy_Hill=Grassy_HillURL;
export const Herd=HerdURL;
export const Holding_Heart_Cat=Holding_Heart_CatURL;
export const IQ200=IQ200URL;
export const King_of_the_hill_barrows_edition=King_of_the_hill_barrows_editionURL;
export const King_of_the_hill_barrows_edition_2=King_of_the_hill_barrows_edition_2URL;
export const Litter_badge=Litter_badgeURL;
export const Mad_House_2=Mad_House_2URL;
export const Name_Butcher_4000=Name_Butcher_4000URL;
export const Nuke=NukeURL;
export const Pumpkin=PumpkinURL;
export const Ring=RingURL;
export const Spaghetti=SpaghettiURL;
export const Wack=WackURL;
export const Wombat=WombatURL;
export const cat_witch=cat_witchURL;
export const didgeridoo=didgeridooURL;
export const doughnut=doughnutURL;
export const factorio=factorioURL;
export const match=matchURL;
export const no1=no1URL;
export const pan=panURL;
export const plunger=plungerURL;
export const poop=poopURL;
export const purple=purpleURL;
export const sausage_sanga=sausage_sangaURL;
export const seaBus=seaBusURL;
export const secret_thong=secret_thongURL;
export const sleep=sleepURL;
export const teapot=teapotURL;
export const thong=thongURL;
